# Generated by Django 3.1.3 on 2021-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year_Established', models.CharField(max_length=50)),
                ('School_Type', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('binary', 'Binary')], max_length=8)),
                ('Boarding', models.CharField(max_length=50)),
                ('Grades', models.CharField(max_length=200)),
                ('Admission_Period', models.DateTimeField()),
                ('Curriculum', models.CharField(max_length=100)),
                ('School_Level', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
            ],
        ),
    ]
