# Generated by Django 3.1.3 on 2021-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20210618_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Admission_Period',
            field=models.CharField(max_length=200),
        ),
    ]
