# Generated by Django 3.1.3 on 2021-06-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210618_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='last_date',
            field=models.CharField(max_length=50),
        ),
    ]
